### ISSUE TITLE
auth()->logout() results in BadRequestHttpException "Token could not be parsed from the request."

### ISSUE THREAD

**Issue by andrewhl** [irazasyed/jwt-auth-guard#13]
In fact, any auth() methods, using JWTAuthGuard, result in this error, unless I have immediately authenticated before. For example:

```
Route::get('/', function () {
    auth()->attempt(['email' => '...', 'password' => '...']);
    dd(auth()->guest()); // false
}
```

This is expected. But then there's this:

```
Route::get('/', function() {
    dd(auth()->guest()); // BadRequestHTTPException "Token could not be parsed from the request."
}
```

I would expect it to return 'true'.

Furthermore, this fails:

```
Route::get('/', function() {
    auth()->attempt(['email' => '...', 'password' => '...']);
    auth()->logout(); // BadRequestHTTPException "Token could not be parsed from the request."
}
```

I'm really confused here. Here is the tail of the stack trace:

```
in JwtAuthGuard.php line 254
at JwtAuthGuard->requireToken() in JwtAuthGuard.php line 194
at JwtAuthGuard->invalidate(true) in JwtAuthGuard.php line 153
at JwtAuthGuard->logout()
at call_user_func_array(array(object(JwtAuthGuard), 'logout'), array()) in AuthManager.php line 282
at AuthManager->__call('logout', array()) in routes.php line 17
at AuthManager->logout() in routes.php line 17
at RouteServiceProvider->{closure}()
```

Why does JWTAuthGuard->logout() call to invalidate(true) which calls to requireToken()? Why do I need the Authorization header to simply logout? Can anyone help clear this up?

**Comment by stueynet** [comment]
+1

**Comment by irazasyed** [comment]
The token is a requirement in order to invalidate. How do you expect it to invalidate if there is no token passed to it?

Besides, It's fully stateless, So it doesn't maintain any state. A token is a must for every request.

When you do `attempt`, you're attempting only for that single request which again is stateless and simply would authorize the user for thing particular request but once the request ends, it no longer has any idea of that user unless you pass the token in subsequent requests and keep refreshing the token.

The logout method is meant to be used when your request has a token (Like for example a logout route).

Also, This Package is simply a wrapper around the dependency, So there are things that are not under my control.

**Comment by irazasyed** [comment]
As far as the reason why guest too is failing, it's because it depends on the `user()` method which checks for a token by calling the `requireToken()` method which if it doesn't find it in a request, it fails.

I'll check with the dependency library and see if we can do something about it.

**Comment by stueynet** [comment]
So how would one persist the token if they are just trying to replace the built in Laravel authentication with JWT authentication. Do we have to set it in a cookie manually? If so do you have an example or any guidance on that? Basically trying to change to JWT based auth so that both our web application and third party apps can consume the same API.

**Comment by irazasyed** [comment]
You could either use cookie or localstorage method.

Check out this: https://laracasts.com/discuss/channels/vue/starter-application-vuejs-laravel-dingo-jwt

It's an app built on top of these APIs. You can use that for reference.

The simplest flow i use is:

```
User Visits Login Page -> They Enter Login Details & Submit -> Backend Validates & Returns New Token -> Token is saved in localstorage -> Next Request, Use the token that was saved -> Token is Valid, The request returns response + refreshed token in headers -> Save the new token and repeat.
```

So when making requests, the tokens are valid for just 1 request. As soon as it sees the token is invalid, then the previous token is removed from localstorage and user gets redirected to login page again. I might open source once i turn it into a bootstrap (I have plans to do that, Since we use this for multiple projects). But it's for VueJS though.

**Comment by irazasyed** [comment]
Can you please test now? (Pull the last commit, Didn't tag yet). Let me know if it works for you.

**Comment by andrewhl** [comment]
Okay, the fix for auth()->guest() works. Please tag it. Thanks!

**Comment by irazasyed** [comment]
Done. Thanks!
