### ISSUE TITLE
[QUESTION] The "jwt-auth"&"jwt.auth" confusing problem

### ISSUE THREAD

**Issue by byhongda** [irazasyed/jwt-auth-guard#28]
Please prefix your issue with one of the following: **[BUG]** **[PROPOSAL]** **[QUESTION]**.

**In raising this issue, I confirm the following (please check boxes):**
- [x] I have read and understood the [contributors guide](CONTRIBUTING.md).
- [x] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [x] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

**My familiarity with the project is as follows (check one):**
- [ ] I have never used the project.
- [ ] I have used the project briefly.
- [x] I have used the project extensively, but have not contributed previously.
- [ ] I am an active contributor to the project.

**My project stack details**
- Framework (Laravel / Lumen): laravel
- Framework Version: 5.2
- JWT Auth Guard Version: 1.0.4
- `tymon/jwt-auth` Version: ^1.0@dev

---

In the latest jwt-auth (1.0 above), there is a LaravelServiceProvider.php file, and the default short key of the "Authenticate::class" middleware is "jwt.auth". Should it be extended from the "jwt.auth" rather than  "jwt-auth" in the JwtAuthGuardServiceProvider.php ?
This is a place easy to make mistakes，especially for beginners. The error is as follows:
`Auth guard driver [api] is not defined.`
BTW. the document need an updating : )

**Comment by irazasyed** [comment]
Hey @byhongda, No. That is a middleware provided by the package while this uses the default middleware that supports multiple guards and this package is a JWT Auth Driver, not a middleware. So what it does right now is fine.

As far as your error is concerned, you have not properly setup the guard in `config/auth.php`. As per the docs, you're supposed to add it to the config:

``` php
// config/auth.php
'guards' => [
    'api' => [
        'driver' => 'jwt-auth',
        'provider' => 'users'
    ],

    // ...
],
```

Under the `guards` array, there should be an `api` key and the payload with the above mentioned options. You can name it anything, instead of `api`, you can name it for example `jwt` and when using it in the middleware or using the `Auth` facade, you would do something like `Auth::guard('jwt')`.

The important part above is the driver which should always be `jwt-auth` and can't be renamed.

Hope that helps!

**Comment by byhongda** [comment]
I did misunderstand the driver and the middleware ~ Thanks for your reply! @irazasyed
